version: '3.8'

services:
  mysql:
    build: .
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ecommerceapp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: sua-imagem-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jobportal
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_data: